### ISSUE TITLE
js

### ISSUE THREAD

**Issue by Bagusgants** [farizrifqi/RepubliK-API#1]
ini perlu buat file js nggk bg

**Comment by farizrifqi** [comment]
mau pakai js (commonjs/esm) atau typescript bisa kok kak

**Comment by Bagusgants** [comment]
maaf kak saya belum paham typescript,cara runningya gimana kak ,tadi saya buat file index.js kemudian saya running error

**Comment by farizrifqi** [comment]
Gausah `git clone` kak, langsung install packagenya aja `npm install republik-api`, lalu tinggal di panggil di file nodejsnya.

**Comment by Bagusgants** [comment]
jadi tinggal buat file jsnya ya kak,terus dipaste code dari readme gitu nggk sih?

**Comment by farizrifqi** [comment]
Nah iya benar, tinggal bikin folder kosong, lalu `npm init`, kemudian install package dan penggunaan sesuai di readme.
