### ISSUE TITLE
BASE_API_URL constant

### ISSUE THREAD

**Issue by 990-arb** [farizrifqi/RepubliK-API#3]
Shouldn't this be unique per user?

Otherwise, could they unite all accounts that used it in one sybil cluster?

**Comment by 3lang3** [comment]
Maybe you can add a proxy parameter @farizrifqi

**Comment by farizrifqi** [comment]
> Otherwise, could they unite all accounts that used it in one sybil cluster?

I'd like to say it should be same on every user but tbh I am not sure since I actually never tried AWS before. But I've tried on different account the request goes to same endpoint.

**Comment by farizrifqi** [comment]
> Maybe you can add a proxy parameter @farizrifqi

Aight I will, just can't decide where should I put the proxy paramter, on the constructor (means all request will use the proxy) or on every functions so people can choose when they want to use the proxy.

**Comment by farizrifqi** [comment]
> Maybe you can add a proxy parameter @farizrifqi

Aight I will, just can't decide where should I put the proxy paramter, on the constructor (means all request will use the proxy) or on every functions so people can choose when they want to use the proxy.

**Comment by 990-arb** [comment]
Adding it on the constructor seems reasonable to apply it for all requests

**Comment by 990-arb** [comment]
@farizrifqi another small thing I noticed that needs to be fixed in package is that parameter for request seems to be changed for like activity, so now instead of postId it's called activityId, otherwise it fails with missing activityId error.
<img width="500" alt="image" src="https://github.com/farizrifqi/RepubliK-API/assets/123076145/26f20b9a-3c40-417d-a62a-7f424e083627">
