### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by 990-arb** [farizrifqi/RepubliK-API#4]
This seems to be an issue as well, as in real case it will be browser agent.
So, they could filter all queries if they log user agent and consider as bots.

<img width="377" alt="image" src="https://github.com/farizrifqi/RepubliK-API/assets/123076145/263d9625-5a2c-4da2-9663-4a7eb39ca15f">

**Comment by farizrifqi** [comment]
How could I put Postman UserAgent there 😓

I've remove the postman useragent and allow to switch to other useragent https://github.com/farizrifqi/RepubliK-API/commit/fb897eef02017ce7088cf2f930a0339c457dd345
